### ISSUE TITLE
Error response from daemon: manifest unknown

### ISSUE THREAD

**Issue by mrmachine** [cshum/imagor#163]
In my compose file I have `image: ghcr.io/cshum/imagor:v0.9.7` and this has been working fine. Recently, I ran `docker system prune` and when I attempted to re-pull I get:

```
$ docker compose pull imagor
[+] Running 0/1
 ⠿ imagor Error                                                                                                                                                                                 1.4s
Error response from daemon: manifest unknown
```

On checking the available tagged releases (https://github.com/cshum/imagor/pkgs/container/imagor/versions?filters%5Bversion_type%5D=tagged), I can see that this version does indeed no longer exist.

Was this an intentional removal? Or does GHCR automatically cull images for older tagged releases?

It seems the tag format has also changed to drop the `v` prefix, which I assume was intentional.

Either way, this was quite surprising and took a few minutes to work out what was going on, as Docker Compose tried to tell me I needed to build my own image to fix the issue (which did not work).

**Comment by cshum** [comment]
Hi it was due to a ghcr action that accidentally deleted all multi-arch ghcr images. 

Since then I also dropped the v prefix to align with docker semantic, and to have both ghcr and docker hub images built with the same script.

Right now only docker hub has 0.9.7. It would be good to have ghcr mirrored all the missing images from docker hub. But I am even more hesitate for another accident (again)….
