### ISSUE TITLE
Is it possible to get bucket url?

### ISSUE THREAD

**Issue by ak4zh** [cshum/imagor#29]
If you are using public s3 bucket for storing the processed image, is it possible to get the direct s3 URL of the image?

**Comment by lifehome** [comment]
Hi,

I think I am running into a very similar question in mind, that I would like to get the bucket URL for the processed image instead of a path with parameters in it.

For example, whenever I uploaded a file and passed `fit-in/1024x1024/filters:format(png)/test.png`, I want it eventually store into my bucket with a random ID like `Xc3dCN4zurEYX7ut.png` and hopefully imagor will return a full url like `https://example.org/﻿﻿Xc3dCN4zurEYX7ut.png` instead of a url with parameters in it.

However, I wonder if imagor does this or not, as I (haven't started trying it out yet but) seeing imagor is an "inline" image processor with extra result storage capability?

-- Ivan

**Comment by cshum** [comment]
Check out result storage path style introduced in imagor v1.1:
https://github.com/cshum/imagor#storage-and-result-storage-path-style

`IMAGOR_RESULT_STORAGE_PATH_STYLE=suffix`

- 166x169/top/foobar.jpg becomes foobar.45d8ebb31bd4ed80c26e.jpg
- 17x19/smart/example.com/foobar becomes example.com/foobar.ddd349e092cda6d9c729

**Comment by Clasyc** [comment]
@cshum Is it possible to add another path style? For example it would be very cool to preserve image size in the name.

`166x169/top/foobar.jpg` becomes `foobar.45d8ebb31bd4ed80c26e_166x169.jpg`
`400x400/top/foobar.jpg` becomes `foobar.45d8ebb31bd4ed80c26e_400x400.jpg`
