### ISSUE TITLE
How to clear cache ？

### ISSUE THREAD

**Issue by suofiya** [cshum/imagor#329]
how to clear Source Storage and Result Storage files if the original  image is changed?

**Comment by leopku** [comment]
Same issue.
Currently I clear files from source storage (minio) manually.

**Comment by leopku** [comment]
After days of recent work. I found some images was not completely saved in both `source storage` and `result storage` because of original image was too big or bad internet situations. If it happened, I must delete bad files in storage and re-request them again.

Is that a good idea about a clear way to clear the cached images?

**Comment by cshum** [comment]
@suofiya there are couple of configs you may try. 
`*-result-storage-expiration` adding expiration to result storage. 
`-imagor-modified-time-check` allows resulting image be reprocessed if source image changed. The downside is the extra modified time lookup every time the result storage is being called.

```
  -file-result-storage-expiration duration
        File Result Storage expiration duration e.g. 24h. Default no expiration
  -imagor-modified-time-check
        Check modified time of result image against the source image. This eliminates stale result but require more lookups
```

@leopku which version of imagor are you using?

**Comment by leopku** [comment]
@cshum Sorry for reply late.

I'll try it in next days.

Thanks again.
