### ISSUE TITLE
SVG files gets black background

### ISSUE THREAD

**Issue by tholden92** [cshum/imagor#330]
Is it possible to serve SVG files without having the transparent background turn black?

I have tried with /filters:fill(none) and /filters:fill(transparent) but they both yield the same result.

It works correctly when i set the format to either webp or png, but then the files are transcoded into a different format, and I do not want that.

**Comment by tholden92** [comment]
I suppose the problem might be that the svgs are transcoded into jpgs and not served directly. And since JPGs does not support transparent backgrounds, a background color is added.

If it is not possible to serve SVGs directly, is it possible to set a default format that SVGs are transcoded to, that supports transparency?

**Comment by nestor-sk** [comment]
Looking at libvips itself, it doesn't look like it supports writing SVGs. Looking at the code, it looks like the default format is JPEG as you mentioned https://github.com/cshum/imagor/blob/0a1dcf5a57ef0a6107bc777526e6968fb3270cbb/vips/process.go#L533

I'm not the maintainer, but I think that taking into account that format can be defined as a filter, creating a configuration to map in-format to out-format defaults could be a bit of an overkill

**Comment by cshum** [comment]
You may test the `raw()` filter which has been added to the master branch:

https://github.com/cshum/imagor/pkgs/container/imagor/74633573?tag=master
```
ghcr.io/cshum/imagor@sha256:ec9c9967cc750111a9a042c58d574de0256e2d4faa56305bd028a0c462e7ed10
```
Adding the `raw()` filter would output the source image directly, also bypassing result storage. 

Example:
```
http://localhost:8000/unsafe/filters:raw()/https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg
```
However, this shall not be set as default behaviour for SVG, because it is very easy to embed malicious content from an untrusted SVG file. Also this would disabled any image processing, which would lead to confusion if this is to be expected.
