### ISSUE TITLE
Image getting squeezed

### ISSUE THREAD

**Issue by leonardo2204** [cshum/imagor#333]
Hi everyone, thanks for the great project!

I'm struggling to understand why some images are getting squeezed when piping through imagor.
Here is my url:
[https://imagor-h3bghbwoxq-uc.a.run.app/gkqCMJllLkhbQHEVpeFiznJq7nI=/400x0/https://storage.googleapis.com/floki-item-images/34049.png](https://imagor-h3bghbwoxq-uc.a.run.app/gkqCMJllLkhbQHEVpeFiznJq7nI=/400x0/https://storage.googleapis.com/floki-item-images/34049.png)

I'm basically resizing every image to 400x0 (no filters or other stuff applied), and I'm getting this strange image. A lot of other images are working fine.
Am I missing something here?

Imagor Version: 1.4.1

Original image:
![34049](https://user-images.githubusercontent.com/1509421/221967020-cee2c441-1e20-4da1-88f6-41681c448df3.png)

Final (bugged) version:
![Screenshot from 2023-02-28 17-09-49](https://user-images.githubusercontent.com/1509421/221967272-253e4304-a2f1-42af-afb3-b7ee56114271.png)

Thanks!

**Comment by nestor-sk** [comment]
Something that happened to me was that I replaced the original image once and with another different one and the service was still returning the processed image from the first image because the path and filter were the same. Just something to check if you can give the image a different name, you can remove the cached processed image, or add a filter (for example 400x1) that is different and see what happens

**Comment by cshum** [comment]
I tired the above image and it seems to be working fine:
```
http://localhost:8000/unsafe/400x0/https://storage.googleapis.com/floki-item-images/34049.png
```
gives the following:

![34049](https://user-images.githubusercontent.com/293790/222691498-d6989415-b08c-4013-bb6d-1f0daf1497ef.png)

If this is cache related, you may do a quick test by adding a dummy filter (any unrecognisable filter would become no-op) such as `ts(1677837918415)`
