### ISSUE TITLE
Potential deadlock when closing reader from Fanout

### ISSUE THREAD

**Issue by sonda2208** [cshum/imagor#349]
Hi,
After debugging the issue mentioned in #297 and #347, I found a potential deadlock in `blob.doInit` method that closes the reader after sniffing the first 512 bytes to detect image type.
Here is my test case.

```go
func TestDeadLock(t *testing.T) {
	buf := []byte("abcdefghi")
	source := io.NopCloser(readerFunc(func(p []byte) (n int, err error) {
		tmp := make([]byte, 3)
		copy(tmp, buf)
		n = copy(p, tmp)
		return
	}))

	factory := New(source, len(buf))
	r := factory.NewReader()

	res := make([]byte, 1)
	n, err := io.ReadAtLeast(r, res, len(res))
	require.NoError(t, err)
	require.NotZero(t, n)

	time.Sleep(1 * time.Second)
	err = r.Close()
	assert.NoError(t, err)

	log.Println("done")
}
```

Because of the deadlock, the `done` will never be printed.
Please help to verify this issue. Thank you.

**Comment by p2004a** [comment]
I've just spend a few hours debugging this stuff from scratch because it was just hanging there for most of the requests.. Once the particular path gets stuck, it's stuck forever until server restarts.

The deadlock happens because channel write in https://github.com/cshum/imagor/blob/master/fanoutreader/fanout.go#L82 blocks while `f.lock.RLock` is locked, which causes `Close` to be unable to acquire lock in https://github.com/cshum/imagor/blob/master/fanoutreader/fanout.go#L142

**Comment by cocorossello** [comment]
This finally solved the last of our problems!. We had to have a scheduler to ping imagor every second and reboot the container in case it hanged, usually once or twice per day.

Thank you!
