### ISSUE TITLE
Feature request: provide file size in metadata endpoint

### ISSUE THREAD

**Issue by cocorossello** [cshum/imagor#396]
It would be useful if imagor would be able to provide the size of the image in the metadata.

Something like
{"bytes":8888....

(or byteCount or fileSize or whatever).

WDYT?

**Comment by cshum** [comment]
This is a bit tricky because `/meta` endpoint mostly retrieves a small part of image data, sufficient to extract image header and metadata. 
Knowing the image size in bytes requires loading/processing the entire image, which is not ideal for metadata endpoint. 

An alternative would be the same image using HEAD requests. It results no body data, but with the `Content-Length` included in header.

**Comment by cocorossello** [comment]
Yes, right. I forgot you menciones that metadata endpoint really read the image. Thanks
