### ISSUE TITLE
should Imagor clean up file-storage and file-result-storage directories after expiration time?

### ISSUE THREAD

**Issue by StepanKuksenko** [cshum/imagor#464]
I have S3 and file storage configured. 

Environment variables related to S3 and file storage:
```
...
S3_ENDPOINT=***
S3_FORCE_PATH_STYLE=***
S3_LOADER_BUCKET=***
FILE_STORAGE_BASE_DIR=***
FILE_STORAGE_EXPIRATION=24h
FILE_RESULT_STORAGE_BASE_DIR=***
FILE_RESULT_STORAGE_EXPIRATION=24h
``` 

I expected that Imagor would store images in the storage for the next 24 hours and remove them after that time, but I recently found out that I have images even older than a month in both storage directories, so the storage used size is growing continuously.
Did I understand correctly how it is supposed to work, or am I wrong and have to clean the directory by myself? 

Thank you

**Comment by cshum** [comment]
The expiration time only caters for invalidating the image during retrieval, based on last modified time. It does not handle deletion for old files. 

This is because the way of automated file deletion/cleanup for different storages under different scenarios are vastly different.

For S3 it is best to rely on its [lifecycle configuration](https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-expire-general-considerations.html) to handle old file deletion, which does not require maintaining any additional services.

For file system the simplest way is to rely on a bash script cron job that find and recursively delete files based on last modified time. As imagor is usually setup with multi instances, it would not be suitable to perform such operations for file system, as it would hit the resource limit easily.

**Comment by StepanKuksenko** [comment]
Thank you for the quick and detailed clarification.
